=== SrirangaDigital/aakarabharati/php/dbnxml/books/bookdetails.dtd
<!ELEMENT books (book+)>
<!ELEMENT book (title,authors,details,publisher)>
<!ATTLIST book id CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT authors (author*)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT details (year,edition,editor,volume,part,pages)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT editor (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT part (#PCDATA)>
<!ELEMENT pages (#PCDATA)>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-details.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM  "bookdetails.dtd">

<books>
	<book id="001" sstitle="">
		<title>ಸಾಮಾಜಿಕ ಸಂಶೋಧನ ವಿಧಾನಗಳು</title>
		<authors>
			<author>ವಿಲಿಯಮ್ ಜೆ. ಗೂಡ್</author>
			<author>ಪಾಲ್ ಕೆ. ಹ್ಯಾಟ್</author>
		</authors>
		<details>
			<year>1995</year>
			<edition>First</edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher>ಕುವೆಂಪು ಕನ್ನಡ ಅಧ್ಯಯನ ಸಂಸ್ಥೆ, ಮೈಸೂರು ವಿಶ್ವವಿದ್ಯಾನಿಲಯ</publisher>
	</book>
	<book id="002" sstitle="">
		<title>ಸಮಾಜಶಾಸ್ತ್ರ ಕೈಪಿಡಿ</title>
		<authors>
			<author>ವಿಲಿಯಂ ಎಫ್. ಆಗ್ಬರ್ನ್</author>
			<author>ಮೆಯರ್ ಎಫ್. ನಿಮ್ಕಾಫ್</author>
		</authors>
		<details>
			<year>1985</year>
			<edition>First</edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher>ಕುವೆಂಪು ಕನ್ನಡ ಅಧ್ಯಯನ ಸಂಸ್ಥೆ, ಮೈಸೂರು ವಿಶ್ವವಿದ್ಯಾನಿಲಯ</publisher>
	</book>
	<book id="003" sstitle="ಮಂಜೇಶ್ವರ ಗೋವಿಂದ ಪೈ">
		<title>ಗೋವಿಂದ ಪೈ ಸಂಶೋಧನ ಸಂಪುಟ</title>
		<authors>
			<author>ಮಂಜೇಶ್ವರ ಗೋವಿಂದ ಪೈ</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="004" sstitle="ಮಂಜೇಶ್ವರ ಗೋವಿಂದ ಪೈ">
		<title>Indiana</title>
		<authors>
			<author>Manjeshwar Govind Pai</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="005" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ವಚನಸಾಹಿತ್ಯ -೧</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಗುಂಜಾಳ ಎಸ್. ಆರ್. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="006" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ವಚನಸಾಹಿತ್ಯ -೨</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಬಸವರಾಜ ಜಗಜಂಪಿ, ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="007" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ವಚನಸಾಹಿತ್ಯ -೩</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಗುಂಡಣ್ಣ ಕಲಬುರ್ಗಿ, ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="008" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ವಚನಸಾಹಿತ್ಯ -೪</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಮಾಳಿ ವಿ. ಎಸ್. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="009" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ವಚನಸಾಹಿತ್ಯ -೫</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಕಲಬುರ್ಗಿ ಎಂ. ಎಂ. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="010" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ವಚನಸಾಹಿತ್ಯ -೬</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ವೀರಣ್ಣ ರಾಜೂರ, ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="011" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ವಚನವಿವೇಚನೆ</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ನಾಗಯ್ಯ ಜೆ. ಎಂ. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="012" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ಕಾವ್ಯಸಾಹಿತ್ಯ-೧</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಮಲ್ಲಾಪುರ ಬಿ. ವಿ. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="013" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ಕಾವ್ಯಸಾಹಿತ್ಯ-೨</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಬಾಳಣ್ಣ ಸೀಗೀಹಳ್ಳಿ , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="014" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ಚರಿತ್ರಸಾಹಿತ್ಯ-೧</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಕೊಪ್ಪಾ ಎಸ್. ಕೆ. , ಡಾ||. ; ಪಡಶೆಟ್ಟಿ ಎಂ. ಎಂ. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="015" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ಚರಿತ್ರಸಾಹಿತ್ಯ-೨</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಮದಭಾವಿ ಎಮ್. ಎಸ್. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="016" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ಚರಿತ್ರಸಾಹಿತ್ಯ-೩</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಸಿದ್ಧಲಿಂಗ ದೇಸಾಯಿ, ಶ್ರೀ</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="017" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ಲೇಖನಸಾಹಿತ್ಯ-೧</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಪಾಟೀಲ ಬಿ. ಎಂ. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="018" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ಲೇಖನಸಾಹಿತ್ಯ-೨</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ರಾಠೋಡ ಪಿ. ಕೆ. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="019" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
		<title>ಲೇಖನಸಾಹಿತ್ಯ-೩</title>
		<authors>
			<author>ಹಳಕಟ್ಟಿ ಫ. ಗು. , ಡಾ||</author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor>ಸರಸ್ವತಿದೇವಿ ಭಗವತಿ, ಡಾ|| ; ಮೇಲಿನಮನಿ ಎಚ್. ಎಸ್. , ಡಾ||</editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="020" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ಜಮಾಖರ್ಚಿನ ಪದ್ಧತಿ</title>
		<authors>
			<author>ಗುಬ್ಬಿ. ಚಿ. ಲಕ್ಷ್ಮೀನಾರಾಯಣ</author>
		</authors>
		<details>
			<year>1913</year>
			<edition>ಒಂದನೆಯ ಮುದ್ರಣ</edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="021" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ಮತ್ಸ್ಯಪುರಾಣಾಂತರ್ಗತ  ರಾಜಧರ್ಮದಟೀಕಾ</title>
		<authors>
			<author></author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="022" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ಲೇಖ್ಯಬೋಧಿನಿ</title>
		<authors>
			<author></author>
		</authors>
		<details>
			<year>1927</year>
			<edition>ಒಂಬತ್ತನೆಯ ಮುದ್ರಣ</edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher>ಟಿ. ಎನ್. ಶ್ರೀನಿವಾಸ ಶೆಟ್ಟಿ</publisher>
	</book>
	<book id="023" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ಭಗವತೀ-ಕಾತ್ಯಾಯನೀ</title>
		<authors>
			<author>ವೆಂಕಟೇಶ ತಿರಕೋ ಕುಲಕರಣಿ ಗಳಗನಾಥ</author>
		</authors>
		<details>
			<year>1919</year>
			<edition>ಮೊದಲನೆಯ ಮುದ್ರಣ</edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="024" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ಬಂಧವಿಮೋಚನ</title>
		<authors>
			<author></author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="025" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ಕರ್ನಾಟಕ ಕಾವ್ಯಮಾಲೆ</title>
		<authors>
			<author></author>
		</authors>
		<details>
			<year></year>
			<edition></edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="026" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ನಾಗವರ್ಮನ ಕನ್ನಡ ಛಂದಸ್ಸು</title>
		<authors>
			<author></author>
		</authors>
		<details>
			<year>1875</year>
			<edition></edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="027" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ಕರ್ಣಾಟ ಭಾಷಾಕರಂ</title>
		<authors>
			<author></author>
		</authors>
		<details>
			<year>1891</year>
			<edition></edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="028" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ಹಗಲಿನ ವಿನೋದ ಕಥೆಗಳು</title>
		<authors>
			<author></author>
		</authors>
		<details>
			<year>1928</year>
			<edition></edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="029" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ತಮಿಳ್ ಮೊದಲನೇ ಪುಸ್ತಕ</title>
		<authors>
			<author></author>
		</authors>
		<details>
			<year>1896</year>
			<edition></edition>
			<editor></editor>
			<volume></volume>
			<part></part>
			<pages></pages>
		</details>
		<publisher></publisher>
	</book>
	<book id="030" sstitle="ಹಳತು ಹೊನ್ನು">
		<title>ಕುಣಿಗಲ ರಾಮಾಶಾಸ್ತ್ರಿಗಳ ಚರಿತ್ರೆ</title>
		<authors>
			<author></author>
		</authors>
		<details>
			<year></year>
