=== SrirangaDigital/aakarabharati/php/dbnxml/books/book.dtd
<!ELEMENT book (s1*|ANY)>
<!ATTLIST book id CDATA #REQUIRED>
<!ELEMENT s1 (s2*|ANY)>
<!ATTLIST s1 page CDATA #REQUIRED>
<!ATTLIST s1 title CDATA #REQUIRED>
<!ATTLIST s1 author CDATA #REQUIRED>
<!ELEMENT s2 (s3*|ANY)>
<!ATTLIST s2 page CDATA #REQUIRED>
<!ATTLIST s2 title CDATA #REQUIRED>
<!ATTLIST s2 author CDATA #REQUIRED>
<!ELEMENT s3 (s4*|ANY)>
<!ATTLIST s3 page CDATA #REQUIRED>
<!ATTLIST s3 title CDATA #REQUIRED>
<!ATTLIST s3 author CDATA #REQUIRED>
<!ELEMENT s4 (#PCDATA)>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-060.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="060">
	<s1 page="0000e-0000f" title="ಎರಡುನುಡಿ" author=""></s1>
	<s1 page="0000g-0000h" title="ಮುನ್ನುಡಿ" author=""></s1>
	<s1 page="0000m-0000m" title="೧. ಅಂದು ಇಂದು" author="ಅಂಬಿಕಾತನಯದತ್ತ"></s1>
	<s1 page="0000n-0000o" title="೨. ಗಾನ" author="ಗೋಪಾಲಕೃಷ್ಣ"></s1>
	<s1 page="0001-0002" title="೩. ಹಕ್ಕಿ ಹಾರುತಿದೆ" author="ಅಂಬಿಕಾತನಯದತ್ತ"></s1>
	<s1 page="0003-0003" title="೪  ಮಯಾಸುರ" author="ರಾಮಚಂದ್ರ"></s1>
	<s1 page="0004-0005" title="೫. ಸಲಿಗೆಯ ಸಲ್ಲಾಪ" author="ಮಧುರ-ಚೆನ್ನ"></s1>
	<s1 page="0006-0006" title="೬. ಮಿಂಚು" author="ಧೂಲಾಸಾಹೇಬ"></s1>
	<s1 page="0007-0010" title="೭. ತುತ್ತಿನ ಚೀಲ" author="ಅಂಬಿಕಾತನಯದತ್ತ"></s1>
	<s1 page="0011-0014" title="೮. ಮೂವತ್ತು ಮೂರು ಕೈ" author="ಅಂಬಿಕಾತನಯದತ್ತ"></s1>
	<s1 page="0015-0016" title="೯. ಕನಸಿನೊಳಗೆ ಕಣಸು" author="ಅಂಬಿಕಾತನಯದತ್ತ"></s1>
	<s1 page="0017-0017" title="೧೦.ಬಿರುಗಾಳಿ " author="ಸಾಲಿರಾಮಚಂದ್ರರಾಯರು"></s1>
	<s1 page="0018-0017" title="೧೧. ಚೆನ್ನ" author="ಜಯಾಶ್ರಯಿ"></s1>
	<s1 page="0019-0020" title="೧೨. ನನ್ನ ಕನ್ನಡ ನಾಡು" author="ಶ್ರೀಧರ"></s1>
	<s1 page="0021-0022" title="೧೩. ಹುಟ್ಟಿದ ಹಬ್ಬ" author="ಸಂಗಮ-ನಾರಾಯಣ"></s1>
	<s1 page="0023-0031" title="೧೪. ನನ್ನ ಶಾಮ" author="ವನಮಾಲಿ"></s1>
	<s1 page="0032-0032" title="೧೫. ಹಂಬಲ" author="ಗಂಗಾಪ್ರಸಾದ"></s1>
	<s1 page="0033-0034" title="೧೬. ಮುದ್ದಿನ ಬಾಲೆ" author="ವಿನಾಯಕ"></s1>
	<s1 page="0035-0035" title="೧೭. ಆಟ" author="ನಾರಾಯಣಶಾಸ್ತ್ರಿ"></s1>
	<s1 page="0036-0040" title="೧೮. ಚೆಲುವಿನ ಬೇಟೆ" author="ಆನಂದಕಂದ"></s1>
	<s1 page="0041-0042" title="೧೯. ಲಲ್ಲೆಯ ನೆನಹು" author="ಶಿವರಾಮ"></s1>
	<s1 page="0043-0043" title="೨೦. `ಏನಾರೆ'" author="ಬಿಂದು ಮಾಧವ"></s1>
	<s1 page="0044-0045" title="೨೧. ಅಯೋಧ್ಯೆ" author="ವಿನಾಯಕ"></s1>
	<s1 page="0046-0047" title="೨೨. ಅಗಲಿದ ಗೆಳೆಯ" author="ಶೇಷ"></s1>
	<s1 page="0048-0048" title="೨೩. ಬೀಸು ತಾಯಿ !" author="ರಂಗನಾಥ"></s1>
	<s1 page="0049-0050" title="೨೪. ಕಂಬನಿ" author="ರಾಮದಾಸ"></s1>
	<s1 page="0051-0052" title="೨೫. ಹೇವವಿರಲಿ" author="ಬಿಂದುಮಾಧವ"></s1>
	<s1 page="0053-0054" title="೨೬. ಶ್ರುತಾಶ್ರುತ ವೀ" author="ಮಧುರ-ಚೆನ್ನ"></s1>
	<s1 page="0055-0056" title="೨೭.ಇಂಚರಂ " author="ಸಾಲಿ ರಾಮಚಂದ್ರರಾಯರು"></s1>
	<s1 page="0057-0058" title="೨೮. ಚೆಲುವು-ಒಲವು" author="ಆನಂದಕಂದ"></s1>
	<s1 page="0059-0061" title="೨೯. ಒರ್ವ ದೇವಿ" author="ರಾಮಚಂದ್ರ"></s1>
	<s1 page="0062-0063" title="೩೦. ನಸುಕು" author="ಪ್ರಲ್ಹಾದ"></s1>
	<s1 page="0064-0064" title="೩೧. ಕೃಷ್ಣೆಗೆ" author="ಚಿದಂಬರ"></s1>
	<s1 page="0065-0066" title="೩೨. ನೀಲಗಿರಿ " author="ಪ್ರಲ್ಹಾದ"></s1>
	<s1 page="0067-0068" title="೩೩. ಬೇಸಗೆ" author="ಲಿಂಗಪ್ಪ"></s1>
	<s1 page="0069-0069" title="೩೪. ಏನಿರಲಿಲ್ಲ ?" author="ರೇವಣ"></s1>
	<s1 page="0070-0072" title="೩೫. ಹೊಸಕಾಲದ ನವಿಲು" author="ರಂಗನಾಥ"></s1>
	<s1 page="0073-0075" title="೩೬. ಎಳೆಯರಾಗುವಾ ! ನಾವು ಗೆಳೆಯರಾಗುವಾ !" author="ರಾಮದಾಸ"></s1>
	<s1 page="0077-0078" title="೩೭. ಕವಿಗಳೂ ಕವಿತೆಗಳೂ - ವರ್ಣಾನುಕ್ರಮದಿಂದ" author=""></s1>
	<s1 page="0079-0080" title="೩೮. ಕವಿತೆಗಳ ಮೊದಲ ಸಾಲುಗಳ ಪರಿವಿಡಿ - ವರ್ಣಾನುಕ್ರಮದಿಂದ" author=""></s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-002.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="002">
	<s1 page="0000ah-0000ai" title="ಮುನ್ನುಡಿ" author="ತಿಪ್ಪೇರುದ್ರಸ್ವಾಮಿ ಎಚ್."></s1>
	<s1 page="0000aj-0000al" title="ವಿಭಾಗ ಸಂಪಾದಕರ ಮಾತು" author="ಪಾರ್ವತಮ್ಮ ಸಿ."></s1>
	<s1 page="0000am-0000an" title="ಅರಿಕೆ" author="ಮಲ್ಲಿನಾಥಯ್ಯ ಡಿ. ಎಚ್."></s1>
	<s1 page="0000o-0000u" title="ಪೀಠಿಕೆ" author="ವಿಲಿಯಂ ಎಫ್. ಆಗ್ ಬರ್ನ್;ಮೆಯರ್ ಎಫ್. ನಿಮ್ ಕಾಫ್"></s1>
	<s1 page="0000av-0000aw" title="ಮೊದಲ ಇಂಗ್ಲಿಷ್ ಆವೃತ್ತಿಗೆ ಪ್ರಸ್ತಾವನೆ" author="ಕಾರ್ಲ್ ಮನ್ ಹೀಮ್"></s1>
	<s1 page="0000aw-0000aw" title="ಐದನೆಯ ಇಂಗ್ಲಿಷ್ ಆವೃತ್ತಿಗೆ ಪ್ರಸ್ತಾವನೆ" author="ಸ್ಟೆಫನ್ ಕೋಟ್ ಗ್ರೋವ್"></s1>
	<s1 page="0001-0042" title="ಭಾಗ ೧ : ಪೀಠಿಕೆ" author="">
		<s2 page="0001-0026" title="೧. ಸಮಾಜಶಾಸ್ತ್ರ ಮತ್ತು ವಿಜ್ಞಾನ" author=""></s2>
		<s2 page="0027-0042" title="೨. ಮಾನವನ ಸಾಮಾಜಿಕ ಜೀವನಕ್ಕೆ ಸಂಬಂಧಪಟ್ಟ ವಿಷಯಗಳು" author=""></s2>
	</s1>
	<s1 page="0043-0139" title="ಭಾಗ ೨ : ಸಮಾಜ" author="">
		<s2 page="0043-0078" title="೩. ಸಂಸ್ಕೃತಿಯ ಪಾತ್ರ" author=""></s2>
		<s2 page="0079-0119" title="೪. ಜೈವಿಕಾಂಶದ ಕೊಡುಗೆ" author=""></s2>
		<s2 page="0120-0139" title="೫. ಸಮಾಜದಲ್ಲಿ ಭೌಗೋಳಿಕಾಂಶ" author=""></s2>
	</s1>
	<s1 page="0140-0266" title="ಭಾಗ ೩ : ಸಾಮೂಹಿಕ ವರ್ತನೆ" author="">
		<s2 page="0141-0193" title="೬. ಸಮೂಹ ಸಂಯೋಜನೆ" author=""></s2>
		<s2 page="0194-0232" title="೭. ಜನಸ್ತೋಮ ಮತ್ತು ಸಾರ್ವಜನಿಕರು" author=""></s2>
		<s2 page="0233-0266" title="೮. ಸಾಮಾಜಿಕ ನಿಯಂತ್ರಣ ಮತ್ತು ಅನುವರ್ತನೆ" author=""></s2>
	</s1>
	<s1 page="0267-0415" title="ಭಾಗ ೪ : ವ್ಯಕ್ತಿತ್ವ" author="">
		<s2 page="0270-0319" title="೯. ಸಮೂಹ ಮತ್ತು ವ್ಯಕ್ತಿತ್ವ" author=""></s2>
		<s2 page="0320-0358" title="೧೦. ಸಂಸ್ಕೃತಿ ಹಾಗೂ ವ್ಯಕ್ತಿತ್ವ" author=""></s2>
		<s2 page="0359-0415" title="೧೧. ಸಮಾಜೀಕರಣ ಹಾಗೂ ಸಾಮಾಜಿಕ ವಿಚಲನೆ" author=""></s2>
	</s1>
	<s1 page="0416-0544" title="ಭಾಗ ೫ : ಮಾನವಜೀವಿ ಪರಿಸರಶಾಸ್ತ್ರ ಹಾಗೂ ಜನಸಂಖ್ಯೆ" author="">
		<s2 page="0417-0475" title="೧೨. ಸಮುದಾಯಗಳು" author=""></s2>
		<s2 page="0476-0495" title="೧೩. ಜನಸಂಖ್ಯೆಯ ಹಂಚಿಕೆ" author=""></s2>
		<s2 page="0496-0544" title="೧೪. ಜನಸಂಖ್ಯೆಯ ಬೆಳವಣಿಗೆ" author=""></s2>
	</s1>
	<s1 page="0545-0932" title="ಭಾಗ ೬ : ಸಾಮಾಜಿಕ ಸಂಘಟನೆ" author="">
		<s2 page="0547-0579" title="೧೫. ಸಾಮಾಜಿಕ ವ್ಯವಸ್ಥೆ" author=""></s2>
		<s2 page="0580-0645" title="೧೬. ಸಾಮಾಜಿಕ ಸ್ತರವಿನ್ಯಾಸ" author=""></s2>
		<s2 page="0646-0700" title="೧೭. ಸಮಾಜ ಹಾಗೂ ಆರ್ಥಿಕ ಸಂಸ್ಥೆಗಳು" author=""></s2>
		<s2 page="0701-0740" title="೧೮. ಸಮಾಜದ ಆಡಳಿತ ಸಂಸ್ಥೆಗಳು" author=""></s2>
		<s2 page="0741-0790" title="೧೯. ಯುದ್ಧ ಹಾಗೂ ಅಂತರರಾಷ್ಟ್ರೀಯ ಸಂಬಂಧಗಳು" author=""></s2>
		<s2 page="0791-0849" title="೨೦. ಧಾರ್ಮಿಕ ಸಂಸ್ಥೆಗಳು" author=""></s2>
		<s2 page="0850-0902" title="೨೧. ಕುಟುಂಬ" author=""></s2>
		<s2 page="0903-0932" title="೨೨. ಸಂಸ್ಥೆಗಳ ಪರಸ್ಪರ ಸಂಬಂಧ" author=""></s2>
	</s1>
	<s1 page="0933-" title="ಭಾಗ ೭ : ಸಾಮಾಜಿಕ ಸಾಂಸ್ಕೃತಿಕ ಬದಲಾವಣೆ" author=""></s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-066.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="066">
	<s1 page="0005-0006" title="Preface" author="Edward P. Rice"></s1>
	<s1 page="0007-0011" title="I. The Kanarese Language and Country" author="Edward P. Rice">
		<s2 page="0007-0007" title="The Dravidian Languages" author=""></s2>
		<s2 page="0007-0008" title="The Kanarese Country" author=""></s2>
		<s2 page="0008-0008" title="The Name of the Language" author=""></s2>
		<s2 page="0008-0009" title="Earliest Specimens" author=""></s2>
		<s2 page="0009-0010" title="The Alphabet and Written Character" author=""></s2>
		<s2 page="0010-0010" title="Historic Changes" author=""></s2>
		<s2 page="0010-0011" title="Influence of Neighbouring Languages" author=""></s2>
	</s1>
	<s1 page="0012-0015" title="II. Periods of the History of Kanarese Literature" author="Edward P. Rice">
		<s2 page="0013-0015" title="Kingdoms and Dynasties of the Kanarese Country" author=""></s2>
	</s1>
	<s1 page="0016-0036" title="III. The Jaina Period to A. D. 1160" author="Edward P. Rice">
		<s2 page="0016-0022" title="The Jaina Religion in the Kanarese Country" author=""></s2>
		<s2 page="0022-0025" title="Writers previous to the Kavirājamārga" author=""></s2>
		<s2 page="0025-0026" title="Stanzas from Kavirājamārga" author=""></s2>
		<s2 page="0026-0033" title="Writers from the Kavirājamārga to the Lingāyat Revival" author=""></s2>
		<s2 page="0033-0036" title="Illustrative Extract from the Pampa Rāmāyaṇa" author=""></s2>
	</s1>
	<s1 page="0037-0041" title="IV. The Rise of Lingayatism (1160)" author="Edward P. Rice">
		<s2 page="0037-0039" title="Basava and the Early Apostles of Lingāyatism" author=""></s2>
		<s2 page="0039-0041" title="Notes on Lingāyatism" author=""></s2>
	</s1>
	<s1 page="0042-0050" title="V. Lingayat Writers from 1160-1600" author="Edward P. Rice">
		<s2 page="0045-0046" title="Stanzas from Somēśvara Śataka" author=""></s2>
		<s2 page="0046-0048" title="The Basava Purāṇa, with Illustrative Extract" author=""></s2>
		<s2 page="0048-0050" title="Later Writers of the Period" author=""></s2>
	</s1>
	<s1 page="0051-0054" title="VI. Jaina Writers of the Lingāyat Period 1160-1600" author="Edward P. Rice"></s1>
	<s1 page="0055-0060" title="The Rise of Vaishnava Literature (1500-1600)" author="Edward P. Rice">
		<s2 page="0055-0057" title="The Vaishṇava Revival" author=""></s2>
		<s2 page="0057-0057" title="Early Vaishṇava Works" author=""></s2>
		<s2 page="0057-0059" title="Translations of Sanskrit Classics" author=""></s2>
		<s2 page="0059-0060" title="Popular Devotional Songs" author=""></s2>
		<s2 page="0060-0060" title="A Song in Praise of Vishṇu" author=""></s2>
	</s1>
	<s1 page="0061-0071" title="VIII. Kanarese Literature in the XVII and XVIII Centuries" author="Edward P. Rice">
		<s2 page="0061-0063" title="Three Eminent Writers" author=""></s2>
		<s2 page="0064-0066" title="Extract from the Jaimini Bhārata" author=""></s2>
		<s2 page="0066-0067" title="Literature at the Court of the Rājas of Mysore" author=""></s2>
		<s2 page="0067-0069" title="Lingāyat, Jaina and Brahmanical Doctrinal Works" author=""></s2>
		<s2 page="0069-0069" title="Verses by Sarvajnya" author=""></s2>
		<s2 page="0069-0071" title="Collections of Short Stories" author=""></s2>
		<s2 page="0071-0071" title="Specimen of Kanarese Humour" author=""></s2>
	</s1>
	<s1 page="0072-0077" title="IX. The Modern Period (XIX Century)" author="Edward P. Rice">
		<s2 page="0072-0074" title="New Classes of Works" author=""></s2>
		<s2 page="0074-0075" title="Mysore Royal Anthem" author=""></s2>
		<s2 page="0075-0077" title="Present Position and Prospects of Kanarese Literature" author=""></s2>
	</s1>
	<s1 page="0078-0081" title="X. Some Characteristics of Kanarese Literature" author="Edward P. Rice"></s1>
	<s1 page="0082-0085" title="XI. Kanarese Grammalans" author="Edward P. Rice"></s1>
	<s1 page="0086-0087" title="XII. Sanskrit Writers in the Kanarese Country" author="Edward P. Rice"></s1>
	<s1 page="0088-0089" title="Leading Dates" author="Edward P. Rice"></s1>
	<s1 page="0090-0090" title="Appendix A. Original Text of Some Stanzas Quoted" author="Edward P. Rice"></s1>
	<s1 page="0091-0092" title="Appendix B. Biblography" author="Edward P. Rice"></s1>
	<s1 page="0093-0101" title="Index" author="Edward P. Rice"></s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-013.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="013">
	<s1 page="0001-0008" title="೧. ಪದಮಂತ್ರಗೋಪ್ಯ" author=""></s1>
	<s1 page="0009-0120" title="೨. ನೂರೊಂದರ ಹಾಡುಗಳು" author=""></s1>
	<s1 page="0121-0154" title="೩ ಸಟೀಕ ಏಕೋತ್ತರಶತಸ್ಥಲ" author=""></s1>
	<s1 page="0155-0170" title="೪. ಕವಿ ಗುರುಬಸವಕೃತ ಅವಧೂತಗೀತೆ" author=""></s1>
	<s1 page="0171-0204" title="೫. ಪ್ರಾಣಲಿಂಗ ಜ್ಞಾನದರ್ಪಣ ಚಾರಿತ್ರ" author=""></s1>
	<s1 page="0205-0212" title="೬. ಶಿವಯೋಗಾಚರಣೆ" author=""></s1>
	<s1 page="0213-0266" title="೭. ಶಿವಶರಣರ ಪದಗಳು-೧" author=""></s1>
	<s1 page="0267-0292" title="೮. ಹರಳಯ್ಯನ ತ್ರಿಪದಿ" author=""></s1>
	<s1 page="0293-0370" title="೯. ಮೈಲಾರ ಬಸಪ್ಪನ ಶಿವಾನುಭವ ದರ್ಪಣ" author=""></s1>
	<s1 page="0371-0386" title="೧೦. ಹಾನಗಲ್ಲ ಸ್ವಾಮಿಗಳವರು ರಚಿಸಿದ ಹಾಡುಗಬ್ಬಗಳು" author=""></s1>
	<s1 page="0387-0458" title="೧೧. ಬಸವೇಶ್ವರನ ಷಟ್ ಸ್ಥಲ ವಚನದ ಕಥಾಸಾರ" author=""></s1>
	<s1 page="0459-0496" title="೧೨. ನಿರಂಜನ ವಂಶ ರತ್ನಾಕರ" author=""></s1>
	<s1 page="0497-0508" title="೧೩. ಭೈರವೇಶ್ವರಕಾವ್ಯದ ಕಥಾಮಣಿಸೂತ್ರ ರತ್ನಾಕರ" author=""></s1>
	<s1 page="0509-0532" title="೧೪. ವರದಾನಿ ಗುಡ್ದವ್ವೆಯ ಚರಿತ್ರೆ" author=""></s1>
	<s1 page="0533-0788" title="೧೫. ನಾಗಭೂಷಣ ಘನಾಮಠದಾರ್ಯರ ಕೃಷಿಜ್ಞಾನಪ್ರದೀಪಿಕೆ" author=""></s1>
	<s1 page="0789-0846" title="೧೬. ಕೊಡಗಿನ ಸಂಸ್ಥಾನದ ರಾಜೇಂದ್ರನಾಮೆ" author=""></s1>
	<s1 page="0847-0862" title="೧೭. ಕೆಳದಿ ಸಂಸ್ಥಾನದ ರಾಯರ ವಂಶಾವಳಿ" author=""></s1>
</book>

=== SrirangaDigital/aakarabharati/php/dbnxml/books/book-019.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="019">
	<s1 page="0001-0134" title="೧. ಲೇಖನಗಳು" author=""></s1>
	<s1 page="0135-0198" title="೨. ಸಂಪಾದನೆ" author=""></s1>
	<s1 page="0199-0204" title="೩. ಸ್ಫುಟವಿಷಯಗಳು" author=""></s1>
	<s1 page="0205-0216" title="೪. ಗ್ರಂಥಪರಿಚಯ / ವಿಮರ್ಶೆ" author=""></s1>
	<s1 page="0217-0244" title="೫. ಶಿವಾನುಭವ : ಸಹಾಯಧನ/ದೇಣಿಗೆ/ಕಾಣಿಕೆಗಳು" author=""></s1>
	<s1 page="0245-0262" title="೬. ಶಿವಾನುಭವ ಪತ್ರಿಕೆ : ಸೂಚನೆ/ವಿನಂತಿ" author=""></s1>
	<s1 page="0263-0272" title="೭. ಶ್ರದ್ಧಾಂಜಲಿ" author=""></s1>	
	<s1 page="0273-0294" title="೮. ಜಾಹೀರಾತು" author=""></s1>
	<s1 page="0295-0310" title="೯. ಇತರ" author=""></s1>
	<s1 page="0311-0437" title="೧೦. ಶಿವಾನುಭವ ಸಂಚಿಕೆಗಳು ಮತ್ತು ಪರಿವಿಡಿಗಳು" author=""></s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-065.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="065">
	<s1 page="0000g-0000j" title="ಪ್ರಸ್ತಾವನೆ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0001-0011" title="೧ನೆಯ ಪ್ರಕರಣ : ಮಾರುತಿಯ ದೇವಾಲಯ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0011-0021" title="೨ನೆಯ ಪ್ರಕರಣ : ಗುಪ್ತಗುಹೆ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0021-0034" title="೩ನೆಯ ಪ್ರಕರಣ : ಸಾಕ್ಷಾತ್ಕಾರ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0034-0046" title="೪ನೆಯ ಪ್ರಕರಣ : ಸಂಕಟಪ್ರಾಪ್ತಿ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0047-0059" title="೫ನೆಯ ಪ್ರಕರಣ : ಕಾರಾಗೃಹವಾಸ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0060-0073" title="೬ನೆಯ ಪ್ರಕರಣ : ಆಲೋಚನೆ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0074-0088" title="೭ನೆಯ ಪ್ರಕರಣ : ಬಂಧವಿಮೋಚನ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0089-0103" title="೮ನೆಯ ಪ್ರಕರಣ : ಜುಲುಮೆಯ ರಾಮ ರಾಮ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0103-0114" title="೯ನೆಯ ಪ್ರಕರಣ : ಪ್ರತಿಜ್ಞೆ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0115-0121" title="೧೦ನೆಯ ಪ್ರಕರಣ : ದುರಾಲೋಚನೆ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0122-0131" title="೧೧ನೆಯ ಪ್ರಕರಣ : ವಿಚಿತ್ರಯೋಗ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0131-0142" title="೧೨ನೆಯ ಪ್ರಕರಣ : ಹೊಸ ಚಿಂತೆ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0142-0151" title="೧೩ನೆಯ ಪ್ರಕರಣ : ದೈವಸಂಕಲ್ಪ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0152-0162" title="೧೪ನೆಯ ಪ್ರಕರಣ : ಹೆಣ್ಣಿನ ಹೇಸಿ ಆಶೆ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0163-0174" title="೧೫ನೆಯ ಪ್ರಕರಣ : ಸೌಜನ್ಯ ಪ್ರಭಾವ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0175-0186" title="೧೬ನೆಯ ಪ್ರಕರಣ : ಸಮರ್ಥರ ದರ್ಶನ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0186-0196" title="೧೭ನೆಯ ಪ್ರಕರಣ : ಒಳಸಂಚು" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0197-0209" title="೧೮ನೆಯ ಪ್ರಕರಣ : ಇದೇನು ಗದ್ದಲವು ?" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0209-0222" title="೧೯ನೆಯ ಪ್ರಕರಣ : ದುರ್ಗಪ್ರಾಪ್ತಿ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0222-0231" title="೨೦ನೆಯ ಪ್ರಕರಣ : ಸೌಶೀಲ್ಯ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
	<s1 page="0231-0239" title="೨೧ನೆಯ ಪ್ರಕರಣ : ಸತ್ಸಮಾಗಮ ಪ್ರಭಾವ" author="ವೇ. ತಿ. ಗಳಗನಾಥರು"></s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-022.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book id="022" sstitle="ಹಳತು ಹೊನ್ನು">
	<s1 page="0001-0152" title="ವಿದ್ಯಾರ್ಥಿ ಕಾಂಡ" author="">
		<s2 page="0001-0013" title="ಕ್ಷೇಮಸಮಾಚಾರದ ಕಾಗದಗಳು, ಲೇಖನ ಚಿಹ್ನಗಳು, ಒಕ್ಕಣೆ-ಮರಿಯಾದೆ, ಸ್ಥಳ - ಕಾಲ - ವಿಳಾಸ, ಮರಿಯಾದೆಯ ಮಾತುಗಳು, ಬರೆದು ಮುಗಿಸುವಿಕೆ, ವಿಳಾಸ ಬರೆಯುವುದು, ಹೆಚ್ಚು ಮರಿಯಾದೆಯ ಒಕ್ಕಣೆಗಳು" author=""></s2>
		<s2 page="0014-0024" title="ಶ್ರೀ ಶೃಂಗೇರಿ ಮಠಕ್ಕೆ, ಕುಂಭಕೋಣ ಮಠಕ್ಕೆ, ಪುಷ್ಪಗಿರಿ ಮಠಕ್ಕೆ, ವಿರೂಪಾಕ್ಷ, ಕೂಡಲಿ, ಶಿವಗಣ್ಗೆ, ಅವನಿ ಮಠಗಳಿಗೆ, ಶ್ರೀ ಪರಕಾಲ ಮಠಕ್ಕೆ, ಶ್ರೀ ಉತ್ತರಾದಿ ಮಠ, ಶ್ರೀ ವ್ಯಾಸರಾಯ ಮಠ, ಶ್ರೀ ಮದ ಹೋಬಲ ಮಠ, ಶ್ರೀ ರಾಘವೇಂದ್ರಸ್ವಾಮಿ ಮಠ, ವೈಶ್ಯ ಗುರುಗಳಿಗೆ, ಶ್ರೀ ಮುರುಘೇಂದ್ರ ಸ್ವಾಮಿಗಳವರಿಗೆ, ಪಖೀರಸ್ವಾಮಿಗಳವರಿಗೆ, ಶೈವವಿರಕ್ತ ಸಾಮಾನ್ಯರಿಗೆ, ಜೈನ ಮಠಾಧಿಪತಿಗಳಿಗೆ, ಜೈನಬ್ರಾಹ್ಮಣರು ಪರಸ್ಪರ ಬರೆಯುವಿಕೆ, ಜೈನಬ್ರಾಹ್ಮಣೇತರರಿಗೆ, ವಿಶ್ವಕರ್ಮಗುರುಗಳಿಗೆ, ವಿಶ್ವಕರ್ಮ ಸಾಮಾನ್ಯರಿಗೆ, ವೀರಶೈವ ಸಾಮಾನ್ಯರು ಪರಸ್ಪರ ಬರೆಯುವಿಕೆ, ನಗರಸ್ಥ ಲಿಂಗಾಯಿತ ವೈಶ್ಯ ಸಾಮಾನ್ಯರು ಬರೆಯುವಿಕೆ " author=""></s2>
		<s2 page="0024-0044" title="ಹೆಂಡತಿಯು ಗಂಡನಿಗೆ, ಗಂಡನು ಹೆಂಡತಿಗೆ, ನಾಯಕನಿಗೆ ನಾಯಿಕೆಯು, ನಾಯಿಕೆಯು ನಾಯಯಕನಿಗೆ , ಲಗ್ನಪತ್ರಿಕೆ, ಅವುಗಳ ಮುಖ್ಯಾಂಶಗಳು, ಮಗು ಹುಟ್ಟಿದ ಸಮಾಚಾರ, ಊಟಕ್ಕೆ ಕರೆಯುವುದು, ದೇಹಾಲಾಸ್ಯವನ್ನು ಕುರಿತು, ವಿದ್ಯಾರ್ಥಿಯು ತಂದೆಗೆ ಬರೆಯುವಿಕೆ, ಸಾವಿನ ಸುದ್ದಿಯನ್ನು ತಿಳಿಸುವಿಕೆ, ದುಃಖೋಪಶಮನವಾರ್ತೆ, ಅದಕ್ಕೆ  ಪ್ರತ್ಯುತ್ತರ, ಸಾಲವನ್ನು ಕೇಳುವುದು, ಅದನ್ನು ಕೊಡಲು ವೊಪ್ಪಿಕೆ, ಅದಿಲ್ಲವೆಂದು ಹೇಳುವಿಕೆ, ಸಾಲಕ್ಕೆ ತಗಾದೆ, ಅದಕ್ಕೆ ಪ್ರತ್ಯುತ್ತರ, ಮತ್ತೊಂದು ಬಗೆ, ಇನ್ನೊಂದು ಬಗೆ, ಗುಮಾಸ್ತೆ ಬೇಕೆಂದು, ಗುಮಾಸ್ತೆಯ ಹೊಗಳಿಕೆ, ಗುಮಾಸ್ತೆಯ ತಿರಸ್ಕಾರ, ವರ್ತಕರ ಸಾಲದ ಹೊಣೆಗೆ, ಸರಕುಗಳಲ್ಲಿ ಗುಣದೋಷಗಳು, ಅದಕ್ಕೆ ಪ್ರತ್ಯುತ್ತರ, ಭಾಗಸ್ತರ ಸಂಗತಿ, ಸೇರಿಸಿಕೊಂಡದ್ದು, ತಪ್ಪಿಸಿದ್ದು, ಗಂಡನಿಗೆ ಹೆಂಡತಿ ಬರೆಯುವುದು, ಹೆಂಡತಿಗೆ ಗಂಡ ಬರೆಯುವುದು, ಪುಸ್ತಕಗಳು ಬೇಕೆಂದು ಎ ಪಿ ದ್ವಾರ, ಆಕ್ಷೇಪಣೆಗಳು, ಮುದ್ರಾಯಂತ್ರಗಳವರಿಗೆ. " author=""></s2>
		<s2 page="0045-0051" title="" author=""></s2>
	</s1>
	<s1 page="0053-0463" title="ಶಾಸನ ಕಾಂಡ" author="">
	</s1>
	<s1 page="0464-0540" title="ವ್ಯವಹಾರ ಕಾಂಡ" author="">
	</s1>
	<s1 page="0541-0578" title="ಜ್ಞಾನ ಕಾಂಡ" author="">
	</s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-058.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="058">
	<s1 page="0000d-0000d" title="ಉಪೋದ್ಘಾತ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0001-0007" title="1. ಸಸ್ಯಗಳೂ ಜೀವವುಳ್ಳವು" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0007-0017" title="2. ಗಿಡಗಳೂ, ಅವುಗಳ ಅವಯವಗಳೂ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0017-0027" title="3. ಬೀಜ, ಬೀಜಗಳ ಮೊಳೆಯುವಿಕೆ ಮತ್ತು ಮೊಳೆಗಳು" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0028-0035" title="4. ಬೇರು" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0035-0052" title="5. ಪ್ರಕಾಂಡವೂ ಕೊಂಬೆಗಳೂ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0052-0062" title="6. ಎಲೆ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0063-0071" title="7. ಪುಷ್ಪಮಂಜರಿ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0071-0085" title="8. ಹೂವೂ, ಅದರ ಭಾಗಗಳೂ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0086-0096" title="9. ಪುಷ್ಪರೇಣುಸ್ಪರ್ಶವೂ, ಗರ್ಭಧಾರಣವೂ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0096-0109" title="10. ಕಾಯಿಯೂ, ಬೀಜವೂ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0109-0118" title="11. ನೀರು ಒಳಹೊಗುವುದೂ, ಅದರ ಚಲನೆಯೂ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0118-0133" title="12. ಗಿಡಗಳ ಪೋಷಣೆ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0133-0140" title="13. ಗಿಡಗಳ ಬೆಳೆವಳಿಕೆ, ಉಸಿರಾಡುವುದು, ಮತ್ತು ಅವುಗಳ ಭಾಗಗಳ ಚಲನೆ" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
	<s1 page="0140-0147" title="14. ಗಿಡಗಳ ಜಾತಿಗಳು" author="ದಿವಾನ್ ಬಹದ್ದೂರ್ ಕೆ. ರಂಗಾಚಾರ್ಯ"></s1>
</book>
