=== SrirangaDigital/aakarabharati/php/dbnxml/books/book.dtd
<!ELEMENT book (s1*|ANY)>
<!ATTLIST book id CDATA #REQUIRED>
<!ELEMENT s1 (s2*|ANY)>
<!ATTLIST s1 page CDATA #REQUIRED>
<!ATTLIST s1 title CDATA #REQUIRED>
<!ATTLIST s1 author CDATA #REQUIRED>
<!ELEMENT s2 (s3*|ANY)>
<!ATTLIST s2 page CDATA #REQUIRED>
<!ATTLIST s2 title CDATA #REQUIRED>
<!ATTLIST s2 author CDATA #REQUIRED>
<!ELEMENT s3 (s4*|ANY)>
<!ATTLIST s3 page CDATA #REQUIRED>
<!ATTLIST s3 title CDATA #REQUIRED>
<!ATTLIST s3 author CDATA #REQUIRED>
<!ELEMENT s4 (#PCDATA)>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-052.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="052">
	<s1 page="0001-0002" title="ಶ್ರೀಗಣೇಶದ್ವಾದಶನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0003-0003" title="ಶ್ರೀಗಣೇಶದ್ವಾದಶನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0004-0004" title="ಶ್ರೀಗಣೇಶೈಕವಿಂಶತಿನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0005-0005" title="ಶ್ರೀಗಣೇಶೈಕವಿಂಶತಿನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0006-0008" title="ಶ್ರೀಗಣೇಶಾಷ್ಟೋತ್ತರಶತನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0009-0011" title="ಶ್ರೀಗಣೇಶಾಷ್ಟೋತ್ತರಶತನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0012-0014" title="ಗಕಾರಗಣಪತಿಸಹಸ್ರನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0015-0044" title="ಗಕಾರಗಣಪತಿ ಸಹಸ್ರನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0045-0047" title="ಶ್ರೀದಕ್ಷಿಣಾಮೂರ್ತ್ಯಷ್ಟೋತ್ತರಶತನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0048-0051" title="ಶ್ರೀದಕ್ಷಿಣಾಮೂರ್ತ್ಯಷ್ಟೋತ್ತರಶತನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0052-0058" title="ಶ್ರೀಲಲಿತಾಸಹಸ್ರನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0059-0064" title="ಶ್ರೀಲಲಿತಾಸಹಸ್ರನಾಮಪೂರ್ವಪೀಠಿಕೆಯ ಅರ್ಥಾನುವಾದ" author=""></s1>
	<s1 page="0065-0071" title="ಶ್ರೀಲಲಿತಾಸಹಸ್ರನಾಮಪೂರ್ವಪೀಠಿಕೆ" author=""></s1>
	<s1 page="0072-0090" title="ಶ್ರೀಲಲಿತಾಸಹಸ್ರನಾಮಸ್ತೋತ್ರ" author=""></s1>
	<s1 page="0091-0100" title="ಶ್ರೀಲಲಿತಾಸಹಸ್ರನಾಮೋತ್ತರಪೀಠಿಕೆ" author=""></s1>
	<s1 page="0101-0137" title="ಶ್ರೀಲಲಿತಾಸಹಸ್ರನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0138-0141" title="ಶ್ರೀಲಲಿತಾಸಹಸ್ರನಾಮ ವಿಶೇಷವಿಷಯಸಂಗ್ರಹ" author=""></s1>
	<s1 page="0142-0145" title="ಶ್ರೀಲಲಿತಾನಾಮತ್ರಿಶತಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0146-0149" title="ಶ್ರೀಲಲಿತಾನಾಮತ್ರಿಶತೀಪೂರ್ವಪೀಠಿಕೆ" author=""></s1>
	<s1 page="0150-0156" title="ಶ್ರೀಲಲಿತಾನಾಮತ್ರಿಶತೀಸ್ತೋತ್ರ" author=""></s1>
	<s1 page="0156-0160" title="ಶ್ರೀಲಲಿತಾನಾಮತ್ರಿಶತ್ಯುತ್ತರಪೀಠಿಕೆ" author=""></s1>
	<s1 page="0161-0170" title="ಶ್ರೀಲಲಿತಾತ್ರಿಶತೀನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0171-0175" title="ಶ್ರೀಲಲಿತಾಷ್ಟೋತ್ತರಶತನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0176-0179" title="ಶ್ರೀಲಲಿತಾಷ್ಟೋತ್ತರಶತನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0180-0180" title="ಶ್ರೀಲಲಿತಾಪಂಚವಿಂಶತಿನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0181-0181" title="ಶ್ರೀಲಲಿತಾಪಂಚವಿಂಶತಿನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0182-0194" title="ಶ್ರೀಶಿವಸಹಸ್ರನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0195-0225" title="ಶ್ರೀಶಿವಸಹಸ್ರನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0225-0226" title="ಶ್ರೀಶಿವಸಹಸ್ರನಾಮಾವಳಿವಿಶೇಷವಿಚಾರ" author=""></s1>
	<s1 page="0226-0227" title="ಶ್ರೀಶಿವಾಷ್ಟೋತ್ತರಶತನಾಮಾವಳಿಯ ಉಪೋದ್ಘಾತ" author=""></s1>
	<s1 page="0228-0231" title="ಶ್ರೀಶಿವಾಷ್ಟೋತ್ತರಶತನಾಮಾವಳಿ" author=""></s1>
	<s1 page="0231-0231" title="ಶ್ರೀಶಿವದ್ವಾದಶನಾಮಾವಳಿ (ಉಪೋದ್ಘಾತಸಹಿತ)" author=""></s1>
	<s1 page="0232-0232" title="ಶ್ರೀಶಿವಾಷ್ಟನಾಮಾವಳಿ (ಉಪೋದ್ಘಾತಸಹಿತ)" author=""></s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-064.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="064">
	<s1 page="0000b-0000b" title="ಮುನ್ನುಡಿ" author="ನಾಗೇಶ"></s1>
	<s1 page="0001-0009" title="೧ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0009-0017" title="೨ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0017-0025" title="೩ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0025-0034" title="೪ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0034-0040" title="೫ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0040-0049" title="೬ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0050-0057" title="೭ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0057-0068" title="೮ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0068-0077" title="೯ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0077-0083" title="೧೦ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0083-0090" title="೧೧ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0090-0097" title="೧೨ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0097-0103" title="೧೩ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0103-0110" title="೧೪ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0110-0115" title="೧೫ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0115-0122" title="೧೬ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0122-0126" title="೧೭ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0126-0132" title="೧೮ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0133-0141" title="೧೯ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0141-0148" title="೨೦ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0148-0153" title="೨೧ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0153-0159" title="೨೨ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0159-0165" title="೨೩ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
	<s1 page="0166-0170" title="೨೪ನೇ ಪರಿಚ್ಛೇದ" author=""></s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-011.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book id="011" sstitle="ಫ. ಗು. ಹಳಕಟ್ಟಿ">
	<s1 page="0001-0014" title="೧. ಲಿಂಗಪೂಜೆಯ ತತ್ವಗಳು -೧೯೨೬" author=""></s1>
	<s1 page="0015-0026" title="೨. ಲಿಂಗಪೂಜೆಯ ತತ್ವಗಳು -೧೯೩೫" author=""></s1>
	<s1 page="0027-0060" title="೩. ಭಕ್ತಿಯ ವಚನಗಳು" author=""></s1>
	<s1 page="0061-0116" title="೪. ನೈತಿಕ ಮತ್ತು ಭಕ್ತಿಯ ವಚನಗಳು" author=""></s1>
	<s1 page="0117-0150" title="೫. ಪರಮಾತ್ಮನ ಸ್ವರೂಪ" author=""></s1>
	<s1 page="0151-0200" title="೬ ಲಿಂಗ ಮತ್ತು ಪರಮಾತ್ಮ" author=""></s1>
	<s1 page="0201-0286" title="೭. ಶಿವಾನುಭವ ಸತ್ಯಮಾರ್ಗ" author=""></s1>
	<s1 page="0287-0358" title="೮. ಬಸವೇಶ್ವರನ ತತ್ವಗಳು" author=""></s1>
	<s1 page="0359-0386" title="೯. ಶಿವಶರಣರ ಅಹಿಂಸಾಧರ್ಮ" author=""></s1>
	<s1 page="0387-0414" title="೧೦. ಸಂಗೀತದಲ್ಲಿ ಶಿವಶರಣರ ವಚನಗಳು" author=""></s1>
	<s1 page="0415-0500" title="೧೧. Vachnas of Shri Basaveshwara" author=""></s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-059.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="059">
	<s1 page="0003-0003" title="ಹೊಸ ಮುನ್ನುಡಿ" author="ಡಿ. ವಿ. ಗುಂಡಪ್ಪ"></s1>
	<s1 page="0004-0004" title="ಮುನ್ನುಡಿ" author="ಬೆಳ್ಳಾವೆ ವೆಂಕಟನಾರಾಯಣಪ್ಪ"></s1>
	<s1 page="0005-0005" title="ವಿಜ್ಞಾಪನೆ" author="ಡಿ. ವಿ. ಗುಂಡಪ್ಪ"></s1>
	<s1 page="0007-0022" title="ಮೊದಲನೆಯ ಭಾಗ" author="ಡಿ. ವಿ. ಗುಂಡಪ್ಪ">
		<s2 page="0007-0008" title="ಸರಳರಿಗೆ" author=""></s2>
		<s2 page="0009-0010" title="`ಜೀವಗೀತೆ'ಯ ಪ್ರಸ್ತಾವನೆ" author=""></s2>
		<s2 page="0011-0017" title="ಜೀವಗೀತೆ" author=""></s2>
		<s2 page="0017-0017" title="ಸರ್ವಮತ ಸಿದ್ಧಾಂತ" author=""></s2>
		<s2 page="0018-0018" title="`ಆತ್ಮಗೀತೆ'ಯ ಪ್ರಸ್ತಾವನೆ" author=""></s2>
		<s2 page="0019-0020" title="ಆತ್ಮಗೀತೆ" author=""></s2>
		<s2 page="0021-0021" title="ದೇವರೆಲ್ಲಿ ?" author=""></s2>
		<s2 page="0022-0022" title="ಬೇಡಿಕೆ" author=""></s2>
	</s1>
	<s1 page="0023-0048" title="ಎರಡನೆಯ ಭಾಗ" author="ಡಿ. ವಿ. ಗುಂಡಪ್ಪ">
		<s2 page="0023-0023" title="ವಂದೇ ಮಾತರಂ" author=""></s2>
		<s2 page="0025-0025" title="ರಾಮಕೃಷ್ಣ ಪರಮಹಂಸ" author=""></s2>
		<s2 page="0027-0027" title="ರಾಜಾ ರಾಮಮೋಹನ ರಾಯ್" author=""></s2>
		<s2 page="0029-0031" title="ದಾದಾಭಾಯಿ ನವರೋಜಿ" author=""></s2>
		<s2 page="0033-0033" title="ಗೋಪಾಲ ಕೃಷ್ಣ ಗೋಖಲೆ" author=""></s2>
		<s2 page="0035-0035" title="ವಿವೇಕಾನಂದ ಸ್ವಾಮಿ" author=""></s2>
		<s2 page="0037-0037" title="ಬಾಲಗಂಗಾಧರ ತಿಲಕರು" author=""></s2>
		<s2 page="0039-0039" title="ರವೀಂದ್ರನಾಥ್ ಠಾಕೂರ್" author=""></s2>
		<s2 page="0041-0041" title="ಜಗದೀಶ ಚಂದ್ರ ಬೋಸ್" author=""></s2>
		<s2 page="0043-0043" title="ಮೋಕ್ಷಗುಂಡಂ ವಿಶ್ವೇಶ್ವರಯ್ಯ" author=""></s2>
		<s2 page="0045-0045" title="ಮೋಹನದಾಸ್ ಕರಮಚಂದ್ ಗಾಂಧಿ" author=""></s2>
		<s2 page="0047-0047" title="ಶ್ರೀ ಕೃಷ್ಣರಾಜೇಂದ್ರ ಒಡೆಯರವರು" author=""></s2>
		<s2 page="0048-0048" title="ದೇಶಭಕ್ತ ಪ್ರತಿಜ್ಞೆ" author=""></s2>
	</s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-068.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="068">
	<s1 page="0000c-0000d" title="Preface" author="M. S. P."></s1>
	<s1 page="0000f-0000g" title="ಪೀಠಿಕೆ" author="ಮೈ. ಸೂ. ಪು."></s1>
	<s1 page="0001-0033" title="೧. ಅಂಕ " author="ಷೇಕ್ಸ್ ಪೀರ್">
		<s2 page="0001-0012" title="೧ನೇ ಪ್ರಕರಣ &#8212; ಧೊರೆಯ ಅರಮನೆ" author=""></s2>
		<s2 page="0012-0018" title="೨ನೇ ಪ್ರಕರಣ &#8212; ದುಃಖಸಾರನ ಗೃಹ" author=""></s2>
		<s2 page="0018-0019" title="೩ನೇ ಪ್ರಕರಣ &#8212; ಭದ್ರನಾಥನ ಅರಮನೆ" author=""></s2>
		<s2 page="0019-0031" title="೪ನೇ ಪ್ರಕರಣ &#8212; ಭದ್ರನಾಥನ ಅರಮನೆ" author=""></s2>
		<s2 page="0031-0033" title="೫ನೇ ಪ್ರಕರಣ &#8212; ಭದ್ರನಾಥನ ಅರಮನೆಯ ಓಲಗಶಾಲೆ" author=""></s2>
	</s1>
	<s1 page="0033-0056" title="೨ನೇ ಅಂಕ" author="ಷೇಕ್ಸ್ ಪೀರ್">
		<s2 page="0033-0038" title="೧ನೇ ಪ್ರಕರಣ &#8212; ದುಃಖಸಾರನ ಮಂದಿರ" author=""></s2>
		<s2 page="0039-0044" title="೨ನೇ ಪ್ರಕರಣ &#8212; ದುಃಖಸಾರನ ಮಂದಿರ ಮುಂಭಾಗ" author=""></s2>
		<s2 page="0045-0045" title="೩ನೇ ಪ್ರಕರಣ &#8212; ಕಾಡು" author=""></s2>
		<s2 page="0045-0056" title="೪ನೇ ಪ್ರಕರಣ &#8212; ದುಃಖಸಾರನ ಮನೆಯ ಮುಂದೆ &#8212; ನಿಷ್ಕಂಟಕ ಕೋಳವನ್ನು ಅನುಭವಿಸುತ್ತಾ ಇರುವನು" author=""></s2>
	</s1>
	<s1 page="0057-0077" title="೩ನೇ ಅಂಕ" author="ಷೇಕ್ಸ್ ಪೀರ್">
		<s2 page="0057-0058" title="೧ನೇ ಪ್ರಕರಣ &#8212; ಬೆಟ್ಟದ ತಪ್ಪಲು" author=""></s2>
		<s2 page="0059-0061" title="೨ನೇ ಪ್ರಕರಣ &#8212; ತೊಪ್ಪಲಿನ ಮತ್ತೊಂದು ಕಡೆ ಬಿರುಗಾಳಿ ಬೀಸುವುದು" author=""></s2>
		<s2 page="0061-0062" title="೩ನೇ ಪ್ರಕರಣ &#8212; ದುಃಖಸಾರ ಕುಮಂತ್ರರ ಪ್ರವೇಶ" author=""></s2>
		<s2 page="0062-0068" title="೪ನೇ ಪ್ರಕರಣ &#8212; ಬೆಟ್ಟದ ತಪ್ಪಲು, ಗುಹೆ ಮುಂದೆ" author=""></s2>
		<s2 page="0068-0069" title="೫ನೇ ಪ್ರಕರಣ &#8212; ದುಃಖಸಾರನ ಭವನ" author=""></s2>
		<s2 page="0069-0073" title="೬ನೇ ಪ್ರಕರಣ &#8212; ದುಃಖಸಾರನ ಭವನದ ಸಮೀಪದಲ್ಲಿರುವ ತುಡುಕೇ ಮನೆ" author=""></s2>
		<s2 page="0073-0077" title="೭ನೇ ಪ್ರಕರಣ ದುಃಖಸಾರನ ಮಂದಿರ" author=""></s2>
	</s1>
	<s1 page="0078-0104" title="೪ನೇ ಅಂಕ" author="ಷೇಕ್ಸ್ ಪೀರ್">
		<s2 page="0078-0081" title="೧ನೇ ಪ್ರಕರಣ &#8212; ತಪ್ಪಲು" author=""></s2>
		<s2 page="0081-0085" title="೨ನೇ ಪ್ರಕರಣ &#8212; ಭದ್ರನಾಥನ ಅರಮನೆಯ ಮುಂದೆ" author=""></s2>
		<s2 page="0085-0087" title="೩ನೇ ಪ್ರಕರಣ &#8212; ದೇವರೇವಿನ ಹತ್ತರ ಮಾರದೇಶದ ಸೇನೆಯ ಪಾಳಯ" author=""></s2>
		<s2 page="0087-0088" title="೪ನೇ ಪ್ರಕರಣ &#8212; ದೇವರೇವಿನ ಹತ್ತರದ ಪಾಳಯ &#8212; ಒಂದು ಗೂಡಾರದಲ್ಲಿ" author=""></s2>
		<s2 page="0088-0090" title="೫ನೇ ಪ್ರಕರಣ &#8212; ಪ್ರವೇಶ &#8212; ವಿಷಜೆ, ರಾಹುಕ" author=""></s2>
		<s2 page="0090-0100" title="೬ನೇ ಪ್ರಕರಣ &#8212; ದೇವರೇವಿನ ಸಮೀಪದ ಹೊಲಗಳು" author=""></s2>
		<s2 page="0100-0104" title="೭ನೇ ಪ್ರಕರಣ &#8212; ಮಾರದೇಶದ ಪಾಳಯದಲ್ಲಿ ಒಂದು ಗೂಡಾರ. ಧೊರೆ ನಿದ್ರೆಮಾಡುತಾ ಹಾಸುಗೇಮೇಲೆ ಮಲಗಿಕೊಂಡಿರುವನು. ಇಂಪಾದ ಗಾನವಾಗುತಿರುವುದು. ದೊಡ್ಡಮನುಷ್ಯ ಮತ್ತು ಇತರರು ಅಂಗರಕ್ಷಕರಾಗಿರುವರು" author=""></s2>
	</s1>
	<s1 page="0104-0120" title="೫ನೇ ಅಂಕ" author="ಷೇಕ್ಸ್ ಪೀರ್">
		<s2 page="0104-0107" title="೧ನೇ ಪ್ರಕರಣ &#8212; ದೇವರೇವಿನ ಸಮೀಪದಲ್ಲಿ ನೀಲಪುರೀಸೇನೆಯ ಪಾಳಯ" author=""></s2>
		<s2 page="0107-0107" title="೨ನೇ ಪ್ರಕರಣ &#8212; ಎರಡು ಪಾಳಯಕ್ಕೂ ಮಧ್ಯೆ ಮೈದಾನ ಒಳಗೆ ಕೋಲಾಹಲ" author=""></s2>
		<s2 page="0108-0120" title="೩ನೇ ಪ್ರಕರಣ &#8212; ದೇವರೇವಿನ ಸಮೀಪದಲ್ಲಿ ನೀಲಪುರೀ ಸೇನೆಯ ಪಾಳಯ" author=""></s2>
	</s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-056.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="056">
	<s1 page="" title="ಕವನ" author="">
		<s2 page="0001-0001" title="ಕನ್ನಡಿಗನ ಕೊರಗು" author="ತೀ. ನಂ. ಶ್ರೀಕಂಠಯ್ಯ"></s2>
		<s2 page="0002-0003" title="ಪೊದೆಯ ಹಕ್ಕಿ, ಎದೆಯ ಹಕ್ಕಿ" author="ಕೆ. ವಿ. ಪುಟ್ಟಪ್ಪ"></s2>
		<s2 page="0004-0006" title="ಪ್ರತಿಭೆ" author="ತೀ. ನಂ. ಶ್ರೀಕಂಠಯ್ಯ"></s2>
		<s2 page="0007-0008" title="ಕೇಳಿಕೆ" author="ವಿ. ಕೆ. ಪುಟ್ಟರಾಮು"></s2>
		<s2 page="0009-0010" title="ಕವಿತೆಗೆ" author="ತೀ. ನಂ. ಶ್ರೀಕಂಠಯ್ಯ"></s2>
		<s2 page="0011-0014" title="ಹೀರೆಯ ಹೂವು" author="ಕೆ. ವಿ. ಪುಟ್ಟಪ್ಪ"></s2>
		<s2 page="0015-0018" title="ಪಾರಿಜಾತ" author="ತೀ. ನಂ. ಶ್ರೀಕಂಠಯ್ಯ"></s2>
		<s2 page="0019-0021" title="ಹಕ್ಕಿಗೆ" author="ವಿ. ಕೆ. ಪುಟ್ಟರಾಮು"></s2>
		<s2 page="0022-0022" title="ಅರ್ಧಚಂದ್ರ" author="ಕೆ. ವಿ. ಪುಟ್ಟಪ್ಪ"></s2>
		<s2 page="0023-0023" title="ಗುರು" author="ಕೆ. ವಿ. ಪುಟ್ಟಪ್ಪ"></s2>
		<s2 page="0024-0028" title="ಚಟಾಕಿ" author="ಎಲ್. ಗುಂಡಪ್ಪ"></s2>
		<s2 page="0029-0049" title="ಬೊಮ್ಮನಹಳ್ಳಿಯ ಕಿಂದರಿಜೋಗಿ" author="ಕೆ. ವಿ. ಪುಟ್ಟಪ್ಪ"></s2>
		<s2 page="0050-0053" title="ತಾಯಿ" author="ಎಲ್. ಗುಂಡಪ್ಪ"></s2>
		<s2 page="0054-0054" title="ದೇಶಭಕ್ತಿ" author="ತೀ. ನಂ. ಶ್ರೀಕಂಠಯ್ಯ"></s2>
		<s2 page="0055-0055" title="ದೋರಸಮುದ್ರ" author="ಎಲ್. ಗುಂಡಪ್ಪ"></s2>
		<s2 page="0056-0059" title="ಹೋದ ಬಾಳ ಬೆಳಕು" author="ಕೆ. ವಿ. ಪುಟ್ಟಪ್ಪ"></s2>
		<s2 page="0060-0063" title="ಚಿತ್ತ ಕ್ಷೋಭೆ" author="ವಿ. ಕೆ. ಪುಟ್ಟರಾಮು"></s2>
		<s2 page="0064-0067" title="ದೂರು" author="ಎಲ್. ಗುಂಡಪ್ಪ"></s2>
		<s2 page="0068-0072" title="ನನ್ನ ನಾಯಿ" author="ಪಿ. ಟಿ. ನರಸಿಂಹಾಚಾರ್"></s2>
		<s2 page="0073-0073" title="ಜಿಂಕೆ" author="ವಿ. ಕೆ. ಪುಟ್ಟರಾಮು"></s2>
		<s2 page="0074-0074" title="ವಿಧವೆ" author="ಎಲ್. ಗುಂಡಪ್ಪ"></s2>
		<s2 page="0075-0078" title="ಅಕ್ಕ" author="ಎಲ್. ಗುಂಡಪ್ಪ"></s2>
		<s2 page="0079-0080" title="ಬಯಕೆ" author="ತೀ. ನಂ. ಶ್ರೀಕಂಠಯ್ಯ"></s2>
		<s2 page="0081-0084" title="ತೊರೆ" author="ಪಿ. ಟಿ. ನರಸಿಂಹಾಚಾರ್"></s2>
		<s2 page="0085-0086" title="ಮಲೆನಾಡ ಹುಡುಗಿ" author="ಎಲ್. ಗುಂಡಪ್ಪ"></s2>
		<s2 page="0087-0088" title="ಎರಡು ದಾರಿ" author="ತೀ. ನಂ. ಶ್ರೀಕಂಠಯ್ಯ"></s2>
		<s2 page="0089-0089" title="ಬಿಡುಗಡೆ" author="ಡಿ. ಎಲ್. ನರಸಿಂಹಾಚಾರ್"></s2>
		<s2 page="0090-0090" title="ದೇವನ ಹರಿಕಾರರು (೧)" author="ತೀ. ನಂ. ಶ್ರೀಕಂಠಯ್ಯ"></s2>
		<s2 page="0091-0092" title="ದೇವನ ಹರಿಕಾರರು (೨)" author="ಎಲ್. ಗುಂಡಪ್ಪ"></s2>
		<s2 page="0093-0094" title="ಜೀವನ" author="ಡಿ. ಎಲ್. ನರಸಿಂಹಾಚಾರ್"></s2>
		<s2 page="0095-0096" title="ಆತ್ಮನಿವೇದನ" author="ಕೆ. ವಿ. ಪುಟ್ಟಪ್ಪ"></s2>
	</s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-057.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="057">
	<s1 page="0000g-0000g" title="Foreword" author=""></s1>
	<s1 page="0000k-0000o" title="ಇಂಗ್ಲಿಷ್ ಮಹಾಕವಿಯಾದ ಆಲಿವರ್ ಗೋಲ್ಡಸ್ಮಿತ್ತಿನ ಸಂಕ್ಷಿಪ್ತ ಜೀವನಚರಿತೆ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0001-0006" title="ಮೊದಲನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0006-0010" title="ಎರಡನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0011-0019" title="ಮೂರನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0019-0023" title="ನಾಲ್ಕನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0023-0028" title="ಐದನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0028-0032" title="ಆರನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0033-0037" title="ಏಳನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0038-0047" title="ಎಂಟನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0048-0051" title="ಒಂಬತ್ತನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0052-0056" title="ಹತ್ತನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0057-0062" title="ಹನ್ನೊಂದನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0062-0068" title="ಹನ್ನೆರಡನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0069-0073" title="ಹದಿಮೂರನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0073-0079" title="ಹದಿನಾಲ್ಕನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0080-0085" title="ಹದಿನಯ್ದನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0085-0091" title="ಹದಿನಾರನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0091-0100" title="ಹದಿನೇಳನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0100-0104" title="ಹದಿನೆಂಟನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0104-0108" title="ಹತ್ತೊಂಬತ್ತನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0108-0123" title="ಇಪ್ಪತ್ತನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0123-0132" title="ಇಪ್ಪತ್ತೊಂದನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0132-0136" title="ಇಪ್ಪತ್ತೆರಡನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0136-0140" title="ಇಪ್ಪತ್ತಮೂರನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0140-0145" title="ಇಪ್ಪತ್ತನಾಲ್ಕನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0145-0150" title="ಇಪ್ಪತ್ತಯ್ದನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0150-0155" title="ಇಪ್ಪತ್ತಾರನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0156-0159" title="ಇಪ್ಪತ್ತ ಏಳನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0159-0169" title="ಇಪ್ಪತ್ತ ಎಂಟನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0169-0174" title="ಇಪ್ಪತ್ತ ಒಂಬತ್ತನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0174-0182" title="ಮೂವತ್ತನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0182-0197" title="ಮೂವತ್ತ ಒಂದನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
	<s1 page="0197-0200" title="ಮೂವತ್ತೆರಡನೆಯ ಅಧ್ಯಾಯ" author="ಎಸ್. ಜಿ. ಗೋವಿಂದರಾಜ ಅಯ್ಯಂಗಾರ್ಯ"></s1>
</book>

=== SrirangaDigital/aakarabharati/dbnxml/books/book-001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<book id="001">
	<s1 page="0000g-0000g" title="ಮುನ್ನುಡಿ" author="ಕೆಂಪೇಗೌಡ ಕೆ."></s1>
	<s1 page="0000h-0000h" title="ವಿಭಾಗ ಸಂಪಾದಕರ ಮಾತು" author="ಡಾ. ಸತ್ಯನಾರಾಯಣ"></s1>
	<s1 page="0000i-0000k" title="ಮೊದಲಮಾತು" author="ವಿಲಿಯಮ್ ಜೆ. ಗೂಡ್;ಪಾಲ್ ಕೆ. ಹ್ಯಾಟ್"></s1>
	<s1 page="0000l-0000l" title="ಅನುವಾದಕರ ಅರಿಕೆ" author="ಶಿವಮೂರ್ತಿ ಎಂ."></s1>
	<s1 page="0001-0008" title="೧. ನೂತನ ಸಮಾಜಶಾಸ್ತ್ರ" author=""></s1>
	<s1 page="0009-0025" title="೨. ಸಿದ್ದಾಂತ ಮತ್ತು ವಾಸ್ತವಾಂಶ" author=""></s1>
	<s1 page="0026-0042" title="೩. ಮೌಲ್ಯಗಳು ಮತ್ತು ವಿಜ್ಞಾನ" author=""></s1>
	<s1 page="0042-0059" title="೪. ಶುದ್ಧ ಮತ್ತು ಆನ್ವಯಿಕ ವಿಜ್ಞಾನ" author=""></s1>
	<s1 page="0060-0082" title="೫. ವೈಜ್ಞಾನಿಕ ವಿಧಾನದ ಮೂಲತತ್ತ್ವಗಳು ಮೂಲ ಕಲ್ಪನೆಗಳು" author=""></s1>
	<s1 page="0083-0111" title="೬. ವೈಜ್ಞಾನಿಕ ವಿಧಾನದ ಮೂಲ ಅಂಶಗಳು : ಆಧಾರಕಲ್ಪನೆಗಳು" author=""></s1>
	<s1 page="0112-0136" title="೭. ಸಾಧನೆಯ ವಿನ್ಯಾಸ : ಆಧಾರಕಲ್ಪನೆಯ ಪರಿವೀಕ್ಷಣೆ" author=""></s1>
	<s1 page="0137-0151" title="೮. ಸಂಶೋಧನ ವಿನ್ಯಾಸದಲ್ಲಿ ಮತ್ತಷ್ಟು ಸಮಸ್ಯೆಗಳು" author=""></s1>
	<s1 page="0152-0176" title="೯. ಗ್ರಂಥಾಲಯದ ಬಳಕೆ" author=""></s1>
	<s1 page="0177-0194" title="೧೦. ವೀಕ್ಷಣೆ" author=""></s1>
	<s1 page="0195-0257" title="೧೧. ಪ್ರಶ್ನಾವಳಿಯ ರಚನೆ" author=""></s1>
	<s1 page="0258-0277" title="೧೨. ಅಂಚೆ ಪ್ರಶ್ನಾವಳಿ" author=""></s1>
	<s1 page="0278-0317" title="೧೩. ಸಂದರ್ಶನ" author=""></s1>
	<s1 page="0318-0352" title="೧೪. ಸಂಭವಶಾಸ್ತ್ರ ಮತ್ತು ನಿದರ್ಶನಶಾಸ್ತ್ರ" author=""></s1>
	<s1 page="0353-0368" title="೧೫. ಸ್ಕೇಲಿಂಗ್ ತಂತ್ರಗಳು : ಮೂಲ ಸಮಸ್ಯೆ" author=""></s1>
	<s1 page="0369-0392" title="೧೬. ಸ್ಕೇಲಿಂಗ್ ತಂತ್ರಗಳು : ಸಾಮಾಜಿಕ ಅಂತರದ, ಸಾಮಾಜಿಕ ಮಾಪನಶಾಸ್ತ್ರದ ಹಾಗೂ ತುಲನಾತ್ಮಕ ಸ್ಕೇಲುಗಳು" author=""></s1>
	<s1 page="0393-0453" title="೧೭. ಸ್ಕೇಲಿಂಗ್ ತಂತ್ರಗಳು : ಅನುಕ್ರಮಕರಣದ, ಆಂತಃ ಸುಸಂಬದ್ಧತೆಯ ಹಾಗೂ ಸ್ಕೇಲೋಗ್ರ್ಯಾಮ್ ಸ್ಕೇಲುಗಳು" author=""></s1>
	<s1 page="0454-0480" title="೧೮. ಜನಸಂಖ್ಯಾ ಸಂಶೋಧನೆ" author=""></s1>
	<s1 page="0481-0525" title="೧೯. ಗುಣಾತ್ಮಕ ಮತ್ತು ವಿಶ್ಲೇಷಣೆಯಲ್ಲಿನ ಕೆಲವು ಸಮಸ್ಯೆಗಳು" author=""></s1>
	<s1 page="0526-0551" title="೨೦. ದತ್ತಾಂಶಗಳ ವಿಶ್ಲೇಷಣೆ" author=""></s1>
	<s1 page="0552-0580" title="೨೧. ವರದಿ ತಯಾರಿಕೆ" author=""></s1>
	<s1 page="0581-0592" title="ಪಾರಿಭಾಷಿಕ ಪದಕೋಶ" author=""></s1>
	<s1 page="0593-0599" title="ವಿಷಯಸೂಚಿ" author=""></s1>
</book>
